name: Deploy Frontend Only

on:
  push:
    branches:
      - frontend
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Frontend
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'

          set -e

          cd prod-ci-cd-gasycar

          echo "🔄 Git Pull"
          git reset --hard
          git pull origin main

          echo "🐳 Pull frontend image"
          docker compose pull frontend

          echo "🚀 Restart frontend only"
          docker compose up -d --build frontend

          echo "🧹 Cleanup Docker"
          docker system prune -f

          echo "✅ Frontend déployé sans arrêter les autres services"
          EOF
