name: Reset Database & Media Only

on:
  push:
    branches:
      - db
  workflow_dispatch:


jobs:
  reset-db:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Reset DB & Media on server
        run: |
         
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'

          set -e
          cd prod-ci-cd-gasycar   # 🔁 adapte si besoin

          echo "🛑 Stop services that depend on DB"
          docker compose stop backend frontend || true

          echo "🛑 Stop database"
          docker compose stop db

          echo "🗑️ Remove DB + media volumes"
          docker volume rm prod-ci-cd-gasycar_media_volume prod-ci-cd-gasycar_postgres_data || true

          echo "🚀 Restart services"
          docker compose up -d db
          sleep 10

          docker compose up -d backend frontend

          echo "✅ Database & media reset completed"

          EOF
