name: Deploy Backend Only

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Backend
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
          
          set -e

          cd prod-ci-cd-gasycar

          echo "🔄 Git Pull"
          git reset --hard
          git pull origin main

          echo "🐳 Pull backend image"
          docker compose pull backend

          echo "🚀 Restart backend only"
          docker compose up -d --build backend

          echo "🧹 Cleanup Docker"
          docker system prune -f

          echo "✅ Backend déployé sans toucher les autres services"
          EOF
